/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Juego;
import modelo.Jugador;
import modelo.Pregunta;

/**
 *
 * @author Hp
 */
public class ConcursoPreguntas extends javax.swing.JFrame {

    ControladorJugador conJugador;
    ControladorJuego conJuego;
    ControladorDificultad conDificultad;
    ControladorCategoria conCategoria;
    ControladorOpciones conOpciones;
    ControladorPreguntas conPregunta;
    ControladorPremio conPremio;
    List<Pregunta> listaPreguntas;
    boolean conectado;
    int dificultad = 1;
    int ronda = 1;
    int categoria = 1;
    Pregunta preguntaseleccionada;
    LinkedList<Juego> listaprincipal = new LinkedList<>();
    String nombreJugador;
    String numeroIdentificacion;
    int premioAcumulado = 0;

    /**
     * Creates new form ConcursoPreguntas
     */
    public ConcursoPreguntas() {
        initComponents();
        this.conJugador = new ControladorJugador();
        this.conJuego = new ControladorJuego();
        this.conDificultad = new ControladorDificultad();
        this.conCategoria = new ControladorCategoria();
        this.conOpciones = new ControladorOpciones();
        this.conPregunta = new ControladorPreguntas();
        this.conPremio = new ControladorPremio();
        cargarPreguntas();
        this.listaprincipal = conJuego.Historico();
        this.lista();

    }

    private void lista() {
        DefaultListModel model = new DefaultListModel();
        int index = 0;
        for (Juego juego : listaprincipal) {
            String data = juego.getJugador().getNombres() + " - " + juego.getPremioAcumulado() + " - " + juego.getRonda();
            model.add(index, data);
            index++;
        }
        jList1.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        LbPremioAcumulado = new javax.swing.JLabel();
        lbPremioAcumulado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        txtNombreJugador = new javax.swing.JTextField();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbRonda = new javax.swing.JLabel();
        lbDificultad = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbNumeroPregunta = new javax.swing.JLabel();
        lbPregunta = new javax.swing.JLabel();
        btnOpcion1 = new javax.swing.JButton();
        btnOpcion2 = new javax.swing.JButton();
        btnOpcion3 = new javax.swing.JButton();
        btnOpcion4 = new javax.swing.JButton();
        btnInicarJuego = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbAcumulado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(LbPremioAcumulado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lbPremioAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPremioAcumulado)
                    .addComponent(lbPremioAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historico", jPanel3);

        jLabel11.setText("Nombre  Jugador");

        jLabel12.setText("Numero Identifcacion Jugador");

        btnRegistrarse.setText("Registrate");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(52, 52, 52)
                                .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(76, 76, 76)
                                .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(btnRegistrarse)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnRegistrarse)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro Jugador", jPanel4);

        jLabel1.setText("Pregunta #");

        jLabel2.setText("Opcion 1");

        jLabel3.setText("Opcion 2");

        jLabel4.setText("Opcion 3");

        jLabel5.setText("Opcion 4");

        jLabel8.setText("Ronda");

        jLabel9.setText("Dificultad");

        jLabel10.setText("Categoria");

        lbRonda.setText("jLabel11");

        lbDificultad.setText("jLabel12");

        lbCategoria.setText("jLabel13");

        lbNumeroPregunta.setText("jLabel14");

        lbPregunta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbPregunta.setText("jLabel15");

        btnOpcion1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnOpcion1.setText("jButton1");
        btnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion1ActionPerformed(evt);
            }
        });

        btnOpcion2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnOpcion2.setText("jButton2");
        btnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion2ActionPerformed(evt);
            }
        });

        btnOpcion3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnOpcion3.setText("jButton3");
        btnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion3ActionPerformed(evt);
            }
        });

        btnOpcion4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        btnOpcion4.setText("jButton4");
        btnOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion4ActionPerformed(evt);
            }
        });

        btnInicarJuego.setText("Iniciar Juego");
        btnInicarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicarJuegoActionPerformed(evt);
            }
        });

        jLabel6.setText("Premio Acumulado");

        lbAcumulado.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addComponent(btnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInicarJuego)
                                .addGap(252, 252, 252))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbNumeroPregunta)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel8)
                                .addGap(43, 43, 43)
                                .addComponent(lbRonda)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(lbDificultad)
                                .addGap(105, 105, 105))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(lbCategoria))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(lbAcumulado)))
                        .addGap(151, 151, 151))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbRonda)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(lbNumeroPregunta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(lbDificultad)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbAcumulado)))
                    .addComponent(lbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(btnOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnInicarJuego)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Concurso", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion2ActionPerformed
        verificarRespuesta(this.btnOpcion2.getText());
    }//GEN-LAST:event_btnOpcion2ActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        nombreJugador = txtNombreJugador.getText();
        numeroIdentificacion = txtNumeroIdentificacion.getText();
        conectado = conJugador.CrearJugador(nombreJugador, numeroIdentificacion);
        if (conectado) {
            JOptionPane.showMessageDialog(null, "Jugador creado con exito");
            jTabbedPane1.setSelectedIndex(2);
        } else {
            JOptionPane.showMessageDialog(null, "Jugador no pudo ser registrado");
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnInicarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicarJuegoActionPerformed
        iniciarJuego();
        btnOpcion1.setEnabled(true);
        btnOpcion2.setEnabled(true);
        btnOpcion3.setEnabled(true);
        btnOpcion4.setEnabled(true);
        dificultad = 1;
        ronda = 1;
        categoria = 1;
    }//GEN-LAST:event_btnInicarJuegoActionPerformed

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion1ActionPerformed
        verificarRespuesta(this.btnOpcion1.getText());
    }//GEN-LAST:event_btnOpcion1ActionPerformed

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion3ActionPerformed
        verificarRespuesta(this.btnOpcion3.getText());
    }//GEN-LAST:event_btnOpcion3ActionPerformed

    private void btnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion4ActionPerformed
        verificarRespuesta(this.btnOpcion4.getText());
    }//GEN-LAST:event_btnOpcion4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcursoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcursoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcursoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcursoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcursoPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbPremioAcumulado;
    private javax.swing.JButton btnInicarJuego;
    private javax.swing.JButton btnOpcion1;
    private javax.swing.JButton btnOpcion2;
    private javax.swing.JButton btnOpcion3;
    private javax.swing.JButton btnOpcion4;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAcumulado;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbDificultad;
    private javax.swing.JLabel lbNumeroPregunta;
    private javax.swing.JLabel lbPregunta;
    private javax.swing.JLabel lbPremioAcumulado;
    private javax.swing.JLabel lbRonda;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtNumeroIdentificacion;
    // End of variables declaration//GEN-END:variables

    private void cargarPreguntas() {
        listaPreguntas = (ArrayList<Pregunta>) conPregunta.Buscar_Preguntas();

    }

    private void iniciarJuego() {
        if (conectado) {
            
            preguntaseleccionada = obtenerPregunta();
            if(preguntaseleccionada!=null){
            lbNumeroPregunta.setText("" + ronda);
            lbPregunta.setText(preguntaseleccionada.getDescripcion());
            lbDificultad.setText(preguntaseleccionada.getDificultad().getDescripcion());
            lbCategoria.setText(preguntaseleccionada.getCategoria().getDescripcion());
            lbAcumulado.setText("" + premioAcumulado);
            lbRonda.setText("" + ronda);
            btnOpcion1.setText(preguntaseleccionada.getRespuestas().get(0).getOpcionesRespuesta());
            btnOpcion2.setText(preguntaseleccionada.getRespuestas().get(1).getOpcionesRespuesta());
            btnOpcion3.setText(preguntaseleccionada.getRespuestas().get(2).getOpcionesRespuesta());
            btnOpcion4.setText(preguntaseleccionada.getRespuestas().get(3).getOpcionesRespuesta());
            }
            //premioAcumulado=premioAcumulado+preguntaseleccionada.getValorPremio();
            
        } else {
            JOptionPane.showMessageDialog(this, "por favor registrese para iniciar juego");
        }

    }

    private Pregunta obtenerPregunta() {

        return obtenerPreguntaRandom();

    }

    private Pregunta obtenerPreguntaRandom() {
         if (dificultad > 5) {
            JOptionPane.showMessageDialog(this, "Felicitaciones, ganaste el juego");
            ronda=5;
            guardar_Juego();
            resetearVarible();
        } else {
        int aleatorio = 0;
        aleatorio = (int) (Math.random() * 4);
        return listaPreguntas.stream().filter(f -> f.getDificultad().getId() == dificultad).collect(Collectors.toList()).get(aleatorio);
         }return null;
    }

    private void resetearVarible() {
        dificultad = 1;
        ronda = 1;
        premioAcumulado = 0;
        categoria = 1;
        btnOpcion1.setEnabled(false);
        btnOpcion2.setEnabled(false);
        btnOpcion3.setEnabled(false);
        btnOpcion4.setEnabled(false);
    }

    private void verificarRespuesta(String text) {
       

            int respuestaCorrecta = preguntaseleccionada.getRespuetaCorrecta();
            String textoRespuestaCorrecta = preguntaseleccionada.getRespuestas().stream().filter(f -> f.getId() == respuestaCorrecta).collect(Collectors.toList()).get(0).getOpcionesRespuesta();
            if (textoRespuestaCorrecta.equals(text)) {
                JOptionPane.showMessageDialog(this, "respuesta correcta");
                dificultad++;
                ronda++;
                premioAcumulado = premioAcumulado + preguntaseleccionada.getValorPremio();
                int result = JOptionPane.showConfirmDialog(this, "Desea continuar en el juego", "finalizar juego", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    iniciarJuego();
                } else if (result == JOptionPane.NO_OPTION) {
                    guardar_Juego();
                    resetearVarible();
                }

            } else {
                JOptionPane.showMessageDialog(this, "respuesta incorrecta");
                guardar_Juego();
                lbAcumulado.setText("0");
                resetearVarible();
            }
        

    }

    public void guardar_Juego() {
        // premioAcumulado = Integer.parseInt(lbAcumulado.getText());
        Jugador jugador = new Jugador(nombreJugador, numeroIdentificacion);
        Juego juego = new Juego(jugador, premioAcumulado, ronda);
        conJuego.guardar_Juego(juego);
        JOptionPane.showMessageDialog(this, "juego guardado");

    }

}
